name: investhub_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  cupertino_icons: ^1.0.8
  animated_bottom_navigation_bar: ^1.4.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_core: ^3.7.0
  firebase_messaging: ^15.2.7
  firebase_notifications_handler: ^2.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  flutter_widget_from_html: ^0.17.1
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  rename: ^3.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  states_rebuilder: ^6.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: any
  easy_localization_generator: ^0.3.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/fonts/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 500
        # - asset: assets/fonts/Cairo-SemiBold.ttf
        #   weight: 600
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900

flutter_assets:
  assets_path:
    - assets/images/
    - assets/animations/
  output_path: lib/core/constant/values/
  filename: app_assets.dart
  field_prefix: ""
  classname: AppAssets
  ignore_comments: true


dependency_overrides:
  intl: 0.20.2
